[package]
name = "home-automation"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.1"
dotenv = "0.15.0"
reqwest = { version = "0.12.15", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.44.1", features = ["full"] }
